language: node_js
node_js:
  - "0.10"
addons:
  postgresql: "9.3"
script: "npm test"
before_install:
  - npm install -g pg
env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/ripple_rest_test
notifications:
  email:
    false
